name = "YoRHa Insignia"
prefix = "ire_yorha_insignia"
author = "tsar_bimbo"
version = "1.2.0"

files = [
	"mod.cpp",
	"meta.cpp",
	"logo_yorha_insignia_ca.paa",
]
key_name = "{{author}}"

releasebuild = [
	"@zip ire_yorhainsignia_{{semver.major}}.{{semver.minor}}"
]

